version: '3.8'

services:
  classifier_service:
    build:
      context: ./classifier_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"    # REST API port
    networks:
      - grpc-network

  python_app:
    build:
      context: .
      dockerfile: python_app/Dockerfile
    ports:
      - "50051:50051"  # gRPC port
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge
