# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"&\n\x0f\x43lassifyRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"\x1f\n\x10\x43lassifyResponse\x12\x0b\n\x03tag\x18\x01 \x01(\t2K\n\nClassifier\x12=\n\x08\x43lassify\x12\x16.model.ClassifyRequest\x1a\x17.model.ClassifyResponse\"\x00\x42\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_CLASSIFYREQUEST']._serialized_start=22
  _globals['_CLASSIFYREQUEST']._serialized_end=60
  _globals['_CLASSIFYRESPONSE']._serialized_start=62
  _globals['_CLASSIFYRESPONSE']._serialized_end=93
  _globals['_CLASSIFIER']._serialized_start=95
  _globals['_CLASSIFIER']._serialized_end=170
# @@protoc_insertion_point(module_scope)
